# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(532, 221)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(532, 207))
        MainWindow.setMaximumSize(QtCore.QSize(532, 250))
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3")
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(False)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/Files/Icon/TimeES icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("\n"
"")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.Start_PB = QtWidgets.QPushButton(self.centralwidget)
        self.Start_PB.setGeometry(QtCore.QRect(370, 40, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3 Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.Start_PB.setFont(font)
        self.Start_PB.setStyleSheet("#Start_PB {\n"
"background: #ffffff;\n"
"border-radius: 0px;\n"
"border: 3px solid #656565;\n"
"color:black;\n"
"}\n"
"#Start_PB:hover\n"
"{\n"
"border: 5px solid #00BFF3;\n"
"color:#00bff3\n"
"}\n"
"#Start_PB:pressed\n"
"{\n"
" border: 5px solid #656565;\n"
"color:black;\n"
"}")
        self.Start_PB.setObjectName("Start_PB")
        self.input_AvSp = QtWidgets.QLineEdit(self.centralwidget)
        self.input_AvSp.setGeometry(QtCore.QRect(159, 51, 133, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_AvSp.sizePolicy().hasHeightForWidth())
        self.input_AvSp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3 Bold")
        font.setBold(True)
        font.setWeight(75)
        self.input_AvSp.setFont(font)
        self.input_AvSp.setAutoFillBackground(False)
        self.input_AvSp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_AvSp.setClearButtonEnabled(True)
        self.input_AvSp.setObjectName("input_AvSp")
        self.go_to_Data_PB = QtWidgets.QPushButton(self.centralwidget)
        self.go_to_Data_PB.setGeometry(QtCore.QRect(3, 100, 66, 66))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.go_to_Data_PB.sizePolicy().hasHeightForWidth())
        self.go_to_Data_PB.setSizePolicy(sizePolicy)
        self.go_to_Data_PB.setAutoFillBackground(False)
        self.go_to_Data_PB.setStyleSheet("#go_to_Data_PB {\n"
"background-color: transparent;\n"
"border-image: url(:/go_to_Data/Files/Buttons/go_to_Data/Normal.png);\n"
"background: none;\n"
"border: none;\n"
"background-repeat: none;\n"
"}\n"
"#go_to_Data_PB:hover\n"
"{\n"
"border-image: url(:/go_to_Data/Files/Buttons/go_to_Data/Highlight.png);\n"
"    color:#00bff3\n"
"}\n"
"#go_to_Data_PB:pressed\n"
"{\n"
"border-image: url(:/go_to_Data/Files/Buttons/go_to_Data/Pressed.png);\n"
"    color:black\n"
"}")
        self.go_to_Data_PB.setText("")
        self.go_to_Data_PB.setIconSize(QtCore.QSize(66, 66))
        self.go_to_Data_PB.setObjectName("go_to_Data_PB")
        self.label_AvSp = QtWidgets.QLabel(self.centralwidget)
        self.label_AvSp.setGeometry(QtCore.QRect(41, 51, 112, 18))
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3 Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_AvSp.setFont(font)
        self.label_AvSp.setObjectName("label_AvSp")
        self.input_Si = QtWidgets.QLineEdit(self.centralwidget)
        self.input_Si.setGeometry(QtCore.QRect(160, 111, 133, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_Si.sizePolicy().hasHeightForWidth())
        self.input_Si.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3 Bold")
        font.setBold(True)
        font.setWeight(75)
        self.input_Si.setFont(font)
        self.input_Si.setAutoFillBackground(False)
        self.input_Si.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_Si.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.input_Si.setClearButtonEnabled(True)
        self.input_Si.setObjectName("input_Si")
        self.label_Si = QtWidgets.QLabel(self.centralwidget)
        self.label_Si.setGeometry(QtCore.QRect(120, 111, 29, 18))
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3 Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_Si.setFont(font)
        self.label_Si.setObjectName("label_Si")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 141, 171, 23))
        self.layoutWidget.setObjectName("layoutWidget")
        self.RB_Si = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.RB_Si.setContentsMargins(0, 0, 0, 0)
        self.RB_Si.setObjectName("RB_Si")
        self.RB_MB = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3 Bold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.RB_MB.setFont(font)
        self.RB_MB.setChecked(True)
        self.RB_MB.setObjectName("RB_MB")
        self.RB_Si.addWidget(self.RB_MB)
        self.RB_GB = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3 Bold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.RB_GB.setFont(font)
        self.RB_GB.setChecked(False)
        self.RB_GB.setObjectName("RB_GB")
        self.RB_Si.addWidget(self.RB_GB)
        self.RB_TB = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3 Bold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.RB_TB.setFont(font)
        self.RB_TB.setObjectName("RB_TB")
        self.RB_Si.addWidget(self.RB_TB)
        self.input_Comp = QtWidgets.QLineEdit(self.centralwidget)
        self.input_Comp.setGeometry(QtCore.QRect(440, 110, 37, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_Comp.sizePolicy().hasHeightForWidth())
        self.input_Comp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3 Bold")
        font.setBold(True)
        font.setWeight(75)
        self.input_Comp.setFont(font)
        self.input_Comp.setAutoFillBackground(False)
        self.input_Comp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_Comp.setText("")
        self.input_Comp.setClearButtonEnabled(False)
        self.input_Comp.setObjectName("input_Comp")
        self.label_Perc = QtWidgets.QLabel(self.centralwidget)
        self.label_Perc.setGeometry(QtCore.QRect(480, 110, 21, 18))
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3 Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_Perc.setFont(font)
        self.label_Perc.setObjectName("label_Perc")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(130, 80, 175, 23))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.RB_AvSp = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.RB_AvSp.setContentsMargins(0, 0, 0, 0)
        self.RB_AvSp.setObjectName("RB_AvSp")
        self.RB_KBs = QtWidgets.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3 Bold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.RB_KBs.setFont(font)
        self.RB_KBs.setObjectName("RB_KBs")
        self.RB_AvSp.addWidget(self.RB_KBs)
        self.RB_MBs = QtWidgets.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3 Bold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.RB_MBs.setFont(font)
        self.RB_MBs.setChecked(True)
        self.RB_MBs.setObjectName("RB_MBs")
        self.RB_AvSp.addWidget(self.RB_MBs)
        self.RB_Mbs = QtWidgets.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3 Bold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.RB_Mbs.setFont(font)
        self.RB_Mbs.setObjectName("RB_Mbs")
        self.RB_AvSp.addWidget(self.RB_Mbs)
        self.RB_Mbs.raise_()
        self.RB_KBs.raise_()
        self.RB_MBs.raise_()
        self.Top = QtWidgets.QFrame(self.centralwidget)
        self.Top.setGeometry(QtCore.QRect(0, 0, 541, 21))
        self.Top.setMouseTracking(True)
        self.Top.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top.setObjectName("Top")
        self.win_title = QtWidgets.QLabel(self.Top)
        self.win_title.setGeometry(QtCore.QRect(6, 2, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3 Heavy")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.win_title.setFont(font)
        self.win_title.setStyleSheet("color: rgb(255, 255, 255);")
        self.win_title.setScaledContents(True)
        self.win_title.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.win_title.setOpenExternalLinks(False)
        self.win_title.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.win_title.setObjectName("win_title")
        self.cls_PB = QtWidgets.QPushButton(self.Top)
        self.cls_PB.setGeometry(QtCore.QRect(513, 2, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3 Heavy")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.cls_PB.setFont(font)
        self.cls_PB.setStyleSheet("#cls_PB {\n"
"background-color:#B70F0F;\n"
"border: none;\n"
"background-repeat: none;\n"
"color: rgb(255, 255, 255);\n"
"font: 87 11pt \"Arca Majora 3 Heavy\";\n"
"border-radius: 4px;\n"
"}\n"
"#cls_PB:hover\n"
"{\n"
"background-color:rgb(229, 0, 4);\n"
"}\n"
"#cls_PB:pressed\n"
"{\n"
"background-color: rgb(160, 0, 0);\n"
"}")
        self.cls_PB.setObjectName("cls_PB")
        self.label_Comp = QtWidgets.QLabel(self.centralwidget)
        self.label_Comp.setGeometry(QtCore.QRect(350, 110, 81, 18))
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3 Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_Comp.setFont(font)
        self.label_Comp.setObjectName("label_Comp")
        self.border_left = QtWidgets.QFrame(self.centralwidget)
        self.border_left.setEnabled(False)
        self.border_left.setGeometry(QtCore.QRect(0, 0, 3, 300))
        self.border_left.setStatusTip("")
        self.border_left.setAccessibleName("")
        self.border_left.setAccessibleDescription("")
        self.border_left.setStyleSheet("border: 3px solid black;")
        self.border_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.border_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.border_left.setObjectName("border_left")
        self.border_right = QtWidgets.QFrame(self.centralwidget)
        self.border_right.setEnabled(False)
        self.border_right.setGeometry(QtCore.QRect(529, 0, 3, 300))
        self.border_right.setStatusTip("")
        self.border_right.setAccessibleName("")
        self.border_right.setAccessibleDescription("")
        self.border_right.setStyleSheet("border: 3px solid black;")
        self.border_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.border_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.border_right.setObjectName("border_right")
        self.border_bottom = QtWidgets.QFrame(self.centralwidget)
        self.border_bottom.setEnabled(False)
        self.border_bottom.setGeometry(QtCore.QRect(0, 187, 532, 3))
        self.border_bottom.setStatusTip("")
        self.border_bottom.setAccessibleName("")
        self.border_bottom.setAccessibleDescription("")
        self.border_bottom.setStyleSheet("border: 3px solid black;")
        self.border_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.border_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.border_bottom.setObjectName("border_bottom")
        self.label_Er = QtWidgets.QLabel(self.centralwidget)
        self.label_Er.setEnabled(True)
        self.label_Er.setGeometry(QtCore.QRect(330, 140, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3 Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_Er.setFont(font)
        self.label_Er.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_Er.setObjectName("label_Er")
        self.label_Result = QtWidgets.QLabel(self.centralwidget)
        self.label_Result.setGeometry(QtCore.QRect(0, 182, 517, 31))
        self.label_Result.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3 Bold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_Result.setFont(font)
        self.label_Result.setStyleSheet("color: rgb(19, 125, 37);\n"
"")
        self.label_Result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Result.setObjectName("label_Result")
        self.SpeedTest_PB = QtWidgets.QPushButton(self.centralwidget)
        self.SpeedTest_PB.setGeometry(QtCore.QRect(300, 51, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3 Bold")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.SpeedTest_PB.setFont(font)
        self.SpeedTest_PB.setStyleSheet("#SpeedTest_PB {\n"
"background: #ffffff;\n"
"border-radius: 0px;\n"
"border: 1.5px solid #656565;\n"
"color:black;\n"
"}\n"
"#SpeedTest_PB:hover\n"
"{\n"
"border: 2.5px solid #00BFF3;\n"
"color:#00bff3\n"
"}\n"
"#SpeedTest_PB:pressed\n"
"{\n"
" border: 2.5px solid #656565;\n"
"color:black;\n"
"}")
        self.SpeedTest_PB.setObjectName("SpeedTest_PB")
        self.SizeBrowse_PB = QtWidgets.QPushButton(self.centralwidget)
        self.SizeBrowse_PB.setGeometry(QtCore.QRect(300, 110, 21, 20))
        font = QtGui.QFont()
        font.setFamily("Arca Majora 3 Bold")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.SizeBrowse_PB.setFont(font)
        self.SizeBrowse_PB.setStyleSheet("#SizeBrowse_PB {\n"
"background: #ffffff;\n"
"border-radius: 0px;\n"
"border: 1.5px solid #656565;\n"
"color:black;\n"
"}\n"
"#SizeBrowse_PB:hover\n"
"{\n"
"border: 2.5px solid #00BFF3;\n"
"color:#00bff3\n"
"}\n"
"#SizeBrowse_PB:pressed\n"
"{\n"
" border: 2.5px solid #656565;\n"
"color:black;\n"
"}")
        self.SizeBrowse_PB.setObjectName("SizeBrowse_PB")
        self.loading = QtWidgets.QLabel(self.centralwidget)
        self.loading.setGeometry(QtCore.QRect(370, 160, 91, 21))
        self.loading.setAlignment(QtCore.Qt.AlignCenter)
        self.loading.setObjectName("loading")
        self.border_left.raise_()
        self.Top.raise_()
        self.Start_PB.raise_()
        self.input_AvSp.raise_()
        self.go_to_Data_PB.raise_()
        self.label_AvSp.raise_()
        self.input_Si.raise_()
        self.label_Si.raise_()
        self.layoutWidget.raise_()
        self.input_Comp.raise_()
        self.label_Perc.raise_()
        self.layoutWidget.raise_()
        self.label_Comp.raise_()
        self.border_right.raise_()
        self.border_bottom.raise_()
        self.label_Er.raise_()
        self.label_Result.raise_()
        self.SpeedTest_PB.raise_()
        self.SizeBrowse_PB.raise_()
        self.loading.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_AvSp.setBuddy(self.input_AvSp)
        self.label_Si.setBuddy(self.input_Si)
        self.label_Comp.setBuddy(self.input_Comp)
        self.label_Er.setBuddy(self.input_AvSp)
        self.label_Result.setBuddy(self.input_Si)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.input_AvSp, self.input_Si)
        MainWindow.setTabOrder(self.input_Si, self.RB_KBs)
        MainWindow.setTabOrder(self.RB_KBs, self.RB_MBs)
        MainWindow.setTabOrder(self.RB_MBs, self.RB_Mbs)
        MainWindow.setTabOrder(self.RB_Mbs, self.RB_MB)
        MainWindow.setTabOrder(self.RB_MB, self.RB_GB)
        MainWindow.setTabOrder(self.RB_GB, self.RB_TB)
        MainWindow.setTabOrder(self.RB_TB, self.input_Comp)
        MainWindow.setTabOrder(self.input_Comp, self.Start_PB)
        MainWindow.setTabOrder(self.Start_PB, self.go_to_Data_PB)
        MainWindow.setTabOrder(self.go_to_Data_PB, self.cls_PB)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Time Estimator v5.0 Alpha"))
        self.Start_PB.setToolTip(_translate("MainWindow", "<html><head/><body><p>Start Calculation</p></body></html>"))
        self.Start_PB.setText(_translate("MainWindow", "START"))
        self.input_AvSp.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enter the average transfer speed</p></body></html>"))
        self.go_to_Data_PB.setToolTip(_translate("MainWindow", "<html><head/><body><p>Go to data estimator</p></body></html>"))
        self.label_AvSp.setToolTip(_translate("MainWindow", "<html><head/><body><p>The average transfer speed</p></body></html>"))
        self.label_AvSp.setText(_translate("MainWindow", "Average Speed"))
        self.input_Si.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enter the file/folder size</p></body></html>"))
        self.label_Si.setToolTip(_translate("MainWindow", "<html><head/><body><p>The file/folder size</p></body></html>"))
        self.label_Si.setText(_translate("MainWindow", "Size"))
        self.RB_MB.setToolTip(_translate("MainWindow", "<html><head/><body><p>Change Size units to MegaByte</p></body></html>"))
        self.RB_MB.setText(_translate("MainWindow", "MB"))
        self.RB_MB.setShortcut(_translate("MainWindow", "K"))
        self.RB_GB.setToolTip(_translate("MainWindow", "<html><head/><body><p>Change Size units to GigaByte</p></body></html>"))
        self.RB_GB.setText(_translate("MainWindow", "GB"))
        self.RB_GB.setShortcut(_translate("MainWindow", "M"))
        self.RB_TB.setToolTip(_translate("MainWindow", "<html><head/><body><p>Change Size units to TeraByte</p></body></html>"))
        self.RB_TB.setText(_translate("MainWindow", "TB"))
        self.RB_TB.setShortcut(_translate("MainWindow", "Shift+M"))
        self.input_Comp.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enter how much of the transfer is already done</p></body></html>"))
        self.label_Perc.setText(_translate("MainWindow", "%"))
        self.RB_KBs.setToolTip(_translate("MainWindow", "<html><head/><body><p>Change Speed units to KiloBytes per second</p></body></html>"))
        self.RB_KBs.setText(_translate("MainWindow", "KB/s"))
        self.RB_KBs.setShortcut(_translate("MainWindow", "K"))
        self.RB_MBs.setToolTip(_translate("MainWindow", "<html><head/><body><p>Change Speed units to MegaBytes per second</p></body></html>"))
        self.RB_MBs.setText(_translate("MainWindow", "MB/s"))
        self.RB_MBs.setShortcut(_translate("MainWindow", "M"))
        self.RB_Mbs.setToolTip(_translate("MainWindow", "<html><head/><body><p>Change Speed units to Megabits per second</p></body></html>"))
        self.RB_Mbs.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.RB_Mbs.setText(_translate("MainWindow", "Mb/s"))
        self.RB_Mbs.setShortcut(_translate("MainWindow", "Shift+M"))
        self.win_title.setText(_translate("MainWindow", "Time Estimator V5 Alpha"))
        self.cls_PB.setText(_translate("MainWindow", "x"))
        self.label_Comp.setToolTip(_translate("MainWindow", "<html><head/><body><p>How much of the transfer is already done</p></body></html>"))
        self.label_Comp.setText(_translate("MainWindow", "Completed"))
        self.label_Er.setToolTip(_translate("MainWindow", "<html><head/><body><p>Please recheck the highlighted values (red)</p></body></html>"))
        self.label_Er.setText(_translate("MainWindow", "Provide correct values!"))
        self.label_Result.setToolTip(_translate("MainWindow", "<html><head/><body><p>Result</p></body></html>"))
        self.label_Result.setText(_translate("MainWindow", "res"))
        self.SpeedTest_PB.setText(_translate("MainWindow", "Test"))
        self.SizeBrowse_PB.setText(_translate("MainWindow", "B"))
        self.loading.setText(_translate("MainWindow", "TextLabel"))
import Resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
